### PR TITLE
Fix: Unsubscribe from transport on closing connection

### LINKED ISSUE #11: Performance degradation over time
Hi, first of all, congrats for your amazing project!

I noticed that every connection on the hub register a callback:

    public function subscribe(callable $callback): void
    {
        $this->init();
        $this->subscriber->on('message', function (string $channel, string $payload) use ($callback) {
            $callback($this->serializer->deserialize($payload));
        });
    }

After the client close the connection, the callback remains there.

So, after few hours and hundreds of thousands of subscribes, the performance gets terrible, since every publish has to call hundreds of thousands functions, mostly unecessary (subscriber has long gone).

The solution is to listen connection e close events, register an array of subscribers (address => $callback()), and then remove them on connection close.

That's how the original implementation works: https://github.com/dunglas/mercure/blob/main/subscribe.go

### PR DESCRIPTION
**Pull request by bpolaszek**
Attempt to fix #11

### CODE REVIEW

**Comment by progmancod** [comment]
I thought the correction idea was excellent. Vou testar imediamente. It will be possible to implement the metrics system in the same way. I will do a PR with the implementations of metrics and heartbeat.

**Comment by bpolaszek** [comment]
Hello @progmancod, just pinging 🙂  
Did you get time to test this fix?

**Comment by progmancod** [comment]
Sorry for the delay, it's working very well. I will send you soon PRs for Docker, metrics and hearbeat.

**Comment by bpolaszek** [comment]
Alright, let's merge this! 🎸 

Thank you very much for your support! 👍

**Pull request merged**
