### PR TITLE
Fix dependency on react/async

### LINKED ISSUE #9: Install fails with Composer inside Symfony application
Hi,

I am trying to download this package through Composer.

This is what I get:

```
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires freddie/mercure-x 0.2 -> satisfiable by freddie/mercure-x[0.2].
    - freddie/mercure-x 0.2 requires clue/framework-x dev-main -> found clue/framework-x[dev-main] but it does not match your minimum-stability.
```

If I try to set my minimum-stability to `"dev"`, here is the error:
```
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Restricting packages listed in "symfony/symfony" to "6.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires freddie/mercure-x 0.2 -> satisfiable by freddie/mercure-x[0.2].
    - freddie/mercure-x 0.2 requires react/async dev-main -> found react/async[v1.0.0, 2.x-dev, 3.x-dev, 4.x-dev] but it does not match the constraint.
```

How can I address this issue?

### PR DESCRIPTION
**Pull request by KouloukLeGrand**
Attempting to fix #9 by changing the dependency on `react/async` from branch `"main"` to `"4.x-dev"`.

### CODE REVIEW

**Comment by bpolaszek** [comment]
Hey @KouloukLeGrand  👋 thanks for contributing and for spotting this!

Sounds good, but there's a remaining `composer.lock` conflicts that makes the CI complain. Can you fix this?

Thanks!
Ben

**Comment by KouloukLeGrand** [comment]
> Hey @KouloukLeGrand 👋 thanks for contributing and for spotting this!
> 
> Sounds good, but there's a remaining `composer.lock` conflicts that makes the CI complain. Can you fix this?
> 
> Thanks! Ben

Here you go! Same commit, different branch name 😉

**Comment by bpolaszek** [comment]
Thank you @KouloukLeGrand ! 👍

**Comment by KouloukLeGrand** [comment]
My pleasure, thank you for your reactivity!

**Pull request merged**
